### ISSUE TITLE
For ST2 and/or ST3?

### ISSUE THREAD

**Issue by sandebert** [frankjonen/vorhees#1]
Hi,

The readme claims this is for ST2, but on Package Control it is flagged as available for ST2 *and* ST3. I suggest correcting where it is wrong/incomplete to remove potential confusion.

Thanks

**Comment by frankjonen** [comment]
Thanks for the note. The Sublime Text version is now appropriately set to ST2 instead of all versions. It should be visible in Package Control soon. ST3 is a lot more involved than ST2, so that version will take a while.

**Comment by frankjonen** [comment]
Just pushed a Package Control update and ST3 support. Should be smooth sailing from there on out with updates.
